replicaCount: 1

image:
  repository: hasindubandara/todo-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 3000

env:
  MYSQL_HOST: b1c6cznmpczvwnocjclv-mysql.services.clever-cloud.com
  MYSQL_USERNAME: uptnnvsx8snn1krr
  MYSQL_PASSWORD: LoOofEbpnMuNre8xERnq
  MYSQL_PORT: 3306
  MYSQL_DATABASE: b1c6cznmpczvwnocjclv

resources: {}
