replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/ej-migration/todo-registry/todo-app
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  MYSQL_HOST: b1c6cznmpczvwnocjclv-mysql.services.clever-cloud.com
  MYSQL_USERNAME: uptnnvsx8snn1krr
  MYSQL_PASSWORD: LoOofEbpnMuNre8xERnq
  MYSQL_PORT: 3306
  MYSQL_DATABASE: b1c6cznmpczvwnocjclv

resources: {}
