replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/ej-migration/todo-registry/todo-app
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

serviceaccount:
  name: gkesqlsa
  gsa: todo-k8s-csql@ej-migration.iam.gserviceaccount.com 

resources: {}
